### ISSUE TITLE
plugin incompatible with goland 2023.3

### ISSUE THREAD

**Issue by yo-kel** [geetesh-gupta/JSON-Browser#1]
awesome json viewer!
that's what i need for my json 
i didn't find any other plugins can do the same thing,most of them only pretty json printer
hope if you can update the plugin

**Comment by geetesh-gupta** [comment]
Thanks @yo-kel for the feedback.
Will try to update to latest version once free.

**Comment by geetesh-gupta** [comment]
Hi @yo-kel I have updated the codebase to support latest IDE versions. Kindly validate if working for you with the latest update.

**Comment by yo-kel** [comment]
the plugin now works,thanks for your effort.
